"use client";

import { useEffect, useMemo, useState } from "react";
import { BookOpen, Broadcast, ChartLineUp, Eye, Gauge, GearSix, ShieldWarning } from "@phosphor-icons/react";
import AuthGate from "./components/AuthGate";
import { api, AgentStatus, ActivityLogEntry, LivePosition, OpenPositionDetail, Summary, Trade } from "@/lib/api";

const navItems = [{ label: "Dashboard", icon: Gauge, href: "/" }, { label: "Live Log", icon: Broadcast, href: "/log" }, { label: "Journal", icon: BookOpen, href: "/journal" }, { label: "Coin Watch", icon: Eye, href: "/coins" }, { label: "Risk", icon: ShieldWarning, href: "/risk" }, { label: "Strategy", icon: ChartLineUp, href: "/strategy" }, { label: "Settings", icon: GearSix, href: "/settings" }];

function money(value: number | null | undefined) { return value == null ? "—" : `${value < 0 ? "-" : "+"}$${Math.abs(value).toFixed(2)}`; }
function shortSymbol(value: string) { return value.replace("/USDT:USDT", "").replace("/USDT", "").replace("USDT", ""); }
function CoinMark({ symbol }: { symbol: string }) { return <span className="inline-flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-[#263c55] text-[9px] font-bold text-white">{shortSymbol(symbol).slice(0, 1)}</span>; }
function Header({ agent, halted, onHalt }: { agent: AgentStatus | null; halted: boolean; onHalt: () => void }) { return <header className="fixed left-[186px] right-0 top-0 z-20 flex h-[58px] items-center justify-between border-b border-[#202b35] bg-[#080d12] px-6"><div className="flex items-center gap-5 text-[13px]"><span className="border border-[#2e3e4d] px-4 py-2 font-medium text-[#3b8cff]">{agent?.testnet === false ? "LIVE" : "TESTNET"}</span><span className="flex items-center gap-2 text-[#36d477]"><span className="h-2 w-2 rounded-full bg-current" />{agent?.trading_agent === "ok" ? "Agent Live" : "Agent checking"}</span><span className="h-5 w-px bg-[#334452]" /><span className="text-[#c2ccd5]">Last data sync: <span className="font-mono text-[#dfe7ee]">{agent ? new Date(agent.checked_at).toLocaleTimeString([], { hour12: false }) : "—"} UTC</span></span></div><button onClick={onHalt} className={`border px-4 py-2 text-[12px] font-semibold ${halted ? "border-[#36d477] text-[#36d477]" : "border-[#ff4d54] text-[#ff4d54]"}`}>{halted ? "Resume entries" : "Halt entries"}</button></header>; }

function Sidebar() { return <aside className="fixed inset-y-0 left-0 z-30 flex w-[186px] flex-col border-r border-[#202b35] bg-[#0b1117]"><div className="flex h-[58px] items-center border-b border-[#202b35] px-5 text-[20px] font-semibold text-[#dfe7ee]">Trading<span className="text-[#3b8cff]">AI</span></div><nav className="pt-4">{navItems.map(({ label, icon: Icon, href }) => <a key={label} href={href} className={`flex h-[48px] items-center gap-3 border-l-2 px-5 text-[13px] ${label === "Dashboard" ? "border-[#2e8bff] bg-[#101c29] text-[#3b8cff]" : "border-transparent text-[#c3cdd6] hover:bg-[#10171f]"}`}><Icon size={20} />{label}</a>)}</nav></aside>; }

function MetricStrip({ summary }: { summary: Summary | null }) { const values = [["EQUITY", summary ? `$${summary.bankroll_usdt.toFixed(2)}` : "—", "USDT balance"], ["ROI", summary ? `${summary.roi_pct >= 0 ? "+" : ""}${summary.roi_pct.toFixed(2)}%` : "—", "all-time"], ["REALIZED P&L", summary ? money(summary.total_pnl_usdt) : "—", `${summary?.total_trades ?? 0} closed trades`], ["WIN RATE", summary ? `${summary.win_rate_pct.toFixed(1)}%` : "—", `${summary?.total_trades ?? 0} total`], ["OPEN", summary ? String(summary.open_positions) : "—", "positions"], ["BANKROLL MODE", "Configured", "backend source"]]; return <section className="grid grid-cols-6 border-b border-[#202b35] bg-[#080d12] px-4 py-5">{values.map(([label, value, note], i) => <div key={label} className={`border-r border-[#202b35] px-4 first:pl-1 last:border-r-0 ${i === 0 ? "border-t-2 border-t-[#3186ff]" : ""}`}><div className="mb-2 text-[11px] text-[#9aa6b3]">{label}</div><div className={`font-mono text-[17px] ${value.startsWith("+") ? "text-[#36d477]" : "text-[#e6edf3]"}`}>{value}</div><div className="mt-2 font-mono text-[12px] text-[#b4bec8]">{note}</div></div>)}</section>; }

function OpenPositions({ details, live }: { details: OpenPositionDetail[]; live: LivePosition[] }) { const marks = new Map(live.map((p) => [shortSymbol(p.symbol), p])); return <section className="border-b border-[#202b35]"><div className="border-b border-[#202b35] px-4 py-3 text-[12px] font-medium">OPEN POSITIONS ({details.length})</div><div className="grid grid-cols-[1.2fr_.55fr_1.2fr_1fr_1fr_1fr_1fr_1.4fr] gap-3 border-b border-[#202b35] px-4 py-3 text-[10px] text-[#8d9aa5]"><span>PAIR</span><span>SIDE</span><span>STRATEGY</span><span>OPENED</span><span>UNREALIZED P&L</span><span>ENTRY</span><span>SL / TP</span><span>THESIS / INVALIDATION</span></div>{details.map((item) => { const symbol = shortSymbol(item.trade.symbol); const mark = marks.get(symbol); const snapshot = item.trade.indicator_snapshot as Record<string, unknown>; return <div key={item.trade.id} className="grid grid-cols-[1.2fr_.55fr_1.2fr_1fr_1fr_1fr_1fr_1.4fr] items-start gap-3 border-b border-[#202b35] px-4 py-4 text-[12px]"><div className="flex items-center gap-2"><CoinMark symbol={symbol} /><div><div>{item.trade.symbol}</div><div className="mt-1 text-[10px] text-[#8996a2]">{item.trade.regime} · {item.trade.strategy_name}</div></div></div><div className={item.trade.side.toUpperCase() === "LONG" ? "text-[#36d477]" : "text-[#ff4d54]"}>{item.trade.side.toUpperCase()}</div><div>{item.trade.strategy_name}</div><div className="font-mono text-[11px]">{new Date(item.trade.opened_at).toLocaleString([], { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" })}</div><div className={`font-mono ${mark?.unrealized_pnl != null && mark.unrealized_pnl < 0 ? "text-[#ff4d54]" : "text-[#36d477]"}`}><div>{mark ? money(mark.unrealized_pnl) : "—"}</div><div className="mt-1 text-[10px]">{mark?.roi_pct == null ? "—" : `${mark.roi_pct.toFixed(2)}%`}</div></div><div className="font-mono">{item.trade.entry_price}</div><div className="font-mono">{item.trade.stop_loss}<br />{item.trade.take_profit}</div><div className="leading-[1.35] text-[11px]"><p>{item.reasoning.thesis[0] ?? "No thesis recorded."}</p><p className="mt-1 text-[#ff4d54]">Invalidation: {item.reasoning.invalidation}</p><p className="mt-1 text-[#58b7ff]">Conf: {snapshot.confidence_breakdown && typeof snapshot.confidence_breakdown === "object" ? String((snapshot.confidence_breakdown as Record<string, unknown>).final_confidence ?? "—") : "—"} · EV: {snapshot.mtf_ev == null ? "—" : `${snapshot.mtf_ev}R`}</p></div></div>; })}</section>; }

function RecentTrades({ trades }: { trades: Trade[] }) { const closed = trades.filter((t) => t.closed_at).slice(0, 8); return <section className="border-r border-[#202b35]"><div className="flex items-center justify-between border-b border-[#202b35] px-4 py-3"><h2 className="text-[12px] font-medium">RECENT CLOSED TRADES</h2><a href="/journal" className="text-[12px] text-[#3b8cff]">View all →</a></div>{closed.length ? closed.map((trade) => <div key={trade.id} className="grid grid-cols-[.9fr_1fr_.7fr_1.5fr_1fr] gap-3 border-b border-[#202b35] px-4 py-3 text-[12px]"><span className="font-mono text-[#c5ced7]">{new Date(trade.closed_at!).toLocaleString([], { hour: "2-digit", minute: "2-digit" })}</span><span>{trade.symbol}</span><span className={trade.side.toUpperCase() === "LONG" ? "text-[#36d477]" : "text-[#ff4d54]"}>{trade.side.toUpperCase()}</span><span>{trade.strategy_name}</span><span className={trade.pnl_usdt != null && trade.pnl_usdt < 0 ? "text-[#ff4d54]" : "text-[#36d477]"}>{money(trade.pnl_usdt)}</span></div>) : <div className="p-5 text-[12px] text-[#81909c]">No closed trades in the backend.</div>}<div className="px-4 py-4"><a href="/journal" className="text-[12px] text-[#3b8cff]">View all trades in Journal</a></div></section>; }

function DecisionQueue({ entries }: { entries: ActivityLogEntry[] }) { return <section><div className="flex items-center justify-between border-b border-[#202b35] px-4 py-3"><h2 className="text-[12px] font-medium">AGENT DECISION QUEUE</h2><a href="/log" className="text-[#3b8cff]">View full log →</a></div>{entries.slice(0, 8).map((entry) => <div key={entry.id} className="grid grid-cols-[.9fr_1fr_1.2fr_3fr] gap-3 border-b border-[#202b35] px-4 py-3 text-[12px]"><span className="font-mono text-[#c5ced7]">{new Date(entry.created_at).toLocaleTimeString([], { hour12: false })}</span><span>{entry.symbol ?? "—"}</span><span className={entry.level === "block" ? "text-[#ff4d54]" : entry.level === "open" ? "text-[#36d477]" : "text-[#3b8cff]"}>{(entry.level ?? "info").toUpperCase()}</span><span className="leading-tight text-[#dce4ea]">{entry.message}</span></div>)}</section>; }

function DashboardContent() { const [summary, setSummary] = useState<Summary | null>(null); const [agent, setAgent] = useState<AgentStatus | null>(null); const [details, setDetails] = useState<OpenPositionDetail[]>([]); const [live, setLive] = useState<LivePosition[]>([]); const [trades, setTrades] = useState<Trade[]>([]); const [entries, setEntries] = useState<ActivityLogEntry[]>([]); const [halted, setHalted] = useState(false); const [error, setError] = useState<string | null>(null); const load = () => Promise.all([api.summary(), api.agentStatus(), api.openPositionDetails(), api.livePositions(), api.trades(100), api.activityLog(30)]).then(([s, a, d, l, t, e]) => { setSummary(s); setAgent(a); setDetails(d); setLive(l); setTrades(t); setEntries(e); setHalted(s.kill_switch_active); setError(null); }).catch(() => setError("Could not load dashboard data from the backend.")); useEffect(() => { load(); const timer = window.setInterval(load, 10000); return () => window.clearInterval(timer); }, []); return <div className="min-h-screen min-w-[1486px] bg-[#080d12] font-sans text-[#e6edf3]"><Sidebar /><Header agent={agent} halted={halted} onHalt={() => setHalted(!halted)} /><main className="ml-[186px] min-w-[1486px] overflow-x-auto pt-[58px]">{error && <div className="m-4 border border-[#765b20] bg-[#2a220f] px-3 py-2 text-[11px] text-[#eab83c]">{error}</div>}<MetricStrip summary={summary} /><OpenPositions details={details} live={live} /><div className="grid grid-cols-2"><RecentTrades trades={trades} /><DecisionQueue entries={entries} /></div><footer className="flex items-center justify-between border-t border-[#202b35] px-4 py-3 text-[11px] text-[#8f9aa5]"><span>Backend: <b className="font-normal text-[#36d477]">{agent?.webapi ?? "checking"}</b></span><span>Agent: <b className="font-normal text-[#36d477]">{agent?.trading_agent ?? "checking"}</b></span><span>Refresh: 10s</span></footer></main></div>; }
export default function Page() { return <AuthGate><DashboardContent /></AuthGate>; }
